version: "3.2"
services:
 redis:
    image: "redis:alpine"
    command: redis-server --requirepass RedisPassword
    ports:
     - "6379:6379"
    volumes:
     - $PWD/internal/db/redis/redis-data:/var/lib/redis
     - $PWD/internal/db/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master
    networks:
      node_net:
        ipv4_address: 172.16.1.4
# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24